name: Download
on:
  schedule:
    - cron:  '30 10 * * *'

jobs:
  download:
    name: Download PDF
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch PDF
      run: curl -fsSL https://www.landkreis-bayreuth.de/media/8891/tabelle_gemeinden_covid.pdf -o raw/corona-$(date +%d.%m.%Y).pdf

    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Corona Bot Bayureth
        author_email: corona-bot@localhost.localdomain
        message: "daily auto update"
        add: "raw/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
